### ISSUE TITLE
Remove hardcoding skip = ## in ingest_pdo

### ISSUE THREAD

**Issue by jpshanno** [jpshanno/ingestr#28]
Line 26 of ingest_pdo.R has skip=29 set, which was formerly skip=31, but the HTML format changed. We should try to find a way to automate this value (but the data are not specified as an HTML table so using `r xml2::xml_find_all(pdo_raw, ".//table")` is not the solution)

**Comment by twhiteaker** [comment]
How about skipping lines until the first four characters in the line are "YEAR", or "1900" if 1900 will always be the first year.

**Comment by jpshanno** [comment]
Year that makes sense. It should probably go even further and check the first 2-3 column names before it declares it the start of the table.

**Comment by reblake** [comment]
Pushed changes that fix this in commit 28719c0.
